# Generated by Django 5.2.4 on 2025-12-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asosiyimg', models.ImageField(blank=True, null=True, upload_to='asosiyimg/')),
                ('brenname', models.CharField(max_length=20)),
                ('yetkazishvaqti', models.CharField(max_length=20)),
                ('bepulyetkazish', models.CharField(max_length=20)),
                ('chegirmabilan', models.CharField(max_length=20)),
            ],
        ),
    ]
