# Generated by Django 5.2.4 on 2025-12-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulotlar',
            name='bepulyetkazish',
            field=models.BooleanField(max_length=20),
        ),
    ]
