# Generated by Django 6.0.2 on 2026-08-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_seed_default_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kompaniya nomi')),
                ('icon', models.CharField(default='fa-brands fa-google', help_text='FontAwesome icon, masalan: fa-brands fa-google', max_length=100, verbose_name='Icon')),
                ('icon_color', models.CharField(default='text-blue-500', help_text='Tailwind rang klassi, masalan: text-blue-500', max_length=50, verbose_name='Icon rangi')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Logo rasm (ixtiyoriy)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Hamkor logo',
                'verbose_name_plural': 'Hamkor logolar (carousel)',
                'ordering': ['order'],
            },
        ),
    ]
