# Generated by Django 6.0.2 on 2026-08-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_seed_partners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='icon_color',
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Logo rasm'),
        ),
    ]
