# Generated by Django 6.0.2 on 2026-08-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_remove_partner_icon_remove_partner_icon_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='valuation_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Valuation rasm (WebStorm logosi)'),
        ),
    ]
