# Generated by Django 6.0.2 on 2026-08-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_sitesettings_valuation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name="Hero markaziy rasm (W o'rniga)"),
        ),
    ]
