# Generated by Django 6.0.2 on 2026-08-19 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(default='Web Storm Bot', max_length=100, verbose_name='Bot nomi')),
                ('start_message', models.TextField(default='🚀 WEB STORM\n\nBiznesingiz uchun zamonaviy IT yechimlar.', verbose_name='Start xabar')),
                ('about_text', models.TextField(default='Web Storm — zamonaviy IT kompaniya. Biznesingiz uchun professional yechimlar yaratamiz.', verbose_name='Kompaniya haqida')),
                ('phone', models.CharField(default='+998 XX XXX XX XX', max_length=30, verbose_name='Telefon')),
                ('telegram_username', models.CharField(default='@webstorm', max_length=100, verbose_name='Telegram username')),
                ('instagram', models.CharField(blank=True, default='', max_length=100, verbose_name='Instagram')),
                ('website', models.URLField(blank=True, default='', verbose_name='Website')),
                ('address', models.CharField(blank=True, default='', max_length=300, verbose_name='Manzil')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bot/', verbose_name='Logo')),
                ('is_bot_active', models.BooleanField(default=True, verbose_name='Bot faol')),
            ],
            options={
                'verbose_name': 'Bot sozlamasi',
                'verbose_name_plural': 'Bot sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Familiya')),
                ('username', models.CharField(blank=True, default='', max_length=200, verbose_name='Username')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefon')),
                ('language', models.CharField(default='uz', max_length=10, verbose_name='Til')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Birinchi kirish')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Oxirgi faollik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-first_seen'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Savol-javob',
                'verbose_name_plural': 'Savol-javoblar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Loyiha nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('category', models.CharField(choices=[('crm', 'CRM'), ('bot', 'Telegram Bot'), ('website', 'Web Sayt'), ('webapp', 'Web App'), ('mobile', 'Mobile App'), ('automation', 'Automation')], default='website', max_length=20, verbose_name='Kategoriya')),
                ('technologies', models.CharField(blank=True, default='', max_length=300, verbose_name='Texnologiyalar')),
                ('demo_url', models.URLField(blank=True, default='', verbose_name='Demo URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bot/portfolio/', verbose_name='Preview rasm')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Portfolio loyiha',
                'verbose_name_plural': 'Portfolio loyihalar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='💼', max_length=50, verbose_name='Emoji icon')),
                ('name', models.CharField(max_length=200, verbose_name='Xizmat nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('target_audience', models.CharField(blank=True, default='', max_length=300, verbose_name='Kimlar uchun')),
                ('features', models.TextField(blank=True, default='', verbose_name="Asosiy imkoniyatlar (qator bo'yicha)")),
                ('price_info', models.CharField(default='Narx kelishiladi', max_length=200, verbose_name="Narx ma'lumot")),
                ('image', models.ImageField(blank=True, null=True, upload_to='bot/services/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sayt nomi')),
                ('description', models.TextField(verbose_name='Qisqa tavsif')),
                ('url', models.URLField(verbose_name='URL')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='Kategoriya')),
                ('technologies', models.CharField(blank=True, default='', max_length=300, verbose_name='Texnologiyalar')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bot/websites/', verbose_name='Preview rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Web sayt',
                'verbose_name_plural': 'Web saytlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BotAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin')], default='admin', max_length=20, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_admin_profile', to='bot.botuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Adminlar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('business_type', models.CharField(blank=True, default='', max_length=200, verbose_name='Biznes turi')),
                ('service', models.CharField(max_length=200, verbose_name='Xizmat')),
                ('description', models.TextField(blank=True, default='', verbose_name='Loyiha haqida')),
                ('budget', models.CharField(blank=True, default='', max_length=100, verbose_name='Taxminiy budjet')),
                ('comment', models.TextField(blank=True, default='', verbose_name="Qo'shimcha izoh")),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('contacted', "Bog'lanildi"), ('negotiation', 'Muzokara'), ('waiting', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('in_progress', 'Jarayonda'), ('completed', 'Tugallandi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=20, verbose_name='Holat')),
                ('internal_note', models.TextField(blank=True, default='', verbose_name='Ichki izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.botadmin', verbose_name="Mas'ul admin")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.botuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Paket nomi')),
                ('price', models.CharField(max_length=100, verbose_name='Narx')),
                ('features', models.TextField(verbose_name="Imkoniyatlar (qator bo'yicha)")),
                ('description', models.TextField(blank=True, default='', verbose_name='Tavsif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='bot.service', verbose_name='Xizmat')),
            ],
            options={
                'verbose_name': 'Xizmat paketi',
                'verbose_name_plural': 'Xizmat paketlari',
                'ordering': ['order'],
            },
        ),
    ]
